#!/usr/bin/env python3
"""Acceptance-gate driver used by the three shell suites."""

import argparse
import base64
import gzip
import json
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
import uuid

import jwt


class Client:
    def __init__(self, base):
        self.base = base.rstrip("/")
        self.token = None
        self.org = "org_alaska_001"

    def request(self, method, path, data=None, auth=True, basic=False):
        headers = {"Content-Type": "application/json", "numinar-origin": "mobile", "platform": "android", "x-org-id": self.org}
        if auth and self.token: headers["Authorization"] = "Bearer " + self.token
        if basic: headers["Authorization"] = "Basic " + base64.b64encode(b"admin:testpass123").decode()
        body = None if data is None else json.dumps(data).encode()
        req = urllib.request.Request(self.base + path, data=body, headers=headers, method=method)
        try:
            with urllib.request.urlopen(req, timeout=10) as response:
                raw = response.read()
                return response.status, json.loads(raw) if raw else None, dict(response.headers)
        except urllib.error.HTTPError as exc:
            raw = exc.read()
            return exc.code, json.loads(raw) if raw else None, dict(exc.headers)

    def otp_login(self, email="canvasser@example.test"):
        status, _, _ = self.request("POST", "/passwordless/start", {"client_id": "329jKTvPKBUjOSnY9sYnf0m7Z0gkzTTm", "connection": "email", "email": email, "send": "code", "authParams": {"scope": "openid profile email offline_access", "audience": "https://api.numinar.com", "redirect_uri": "numinar://auth"}}, auth=False)
        check(status == 200, "passwordless/start")
        status, dashboard, _ = self.request("GET", "/__mock/state", auth=False, basic=True)
        check(status == 200, "dashboard OTP read")
        otp = dashboard["otps"][email]["otp"]
        status, tokens, _ = self.request("POST", "/oauth/token", {"grant_type": "http://auth0.com/oauth/grant-type/passwordless/otp", "client_id": "329jKTvPKBUjOSnY9sYnf0m7Z0gkzTTm", "username": email, "otp": otp, "realm": "email", "audience": "https://api.numinar.com", "scope": "openid profile email offline_access"}, auth=False)
        check(status == 200 and all(k in tokens for k in ("access_token", "refresh_token", "id_token", "expires_in")), "OTP token exchange")
        self.token = tokens["access_token"]
        return tokens


def check(condition, label):
    if not condition: raise AssertionError(label)
    print("ok -", label)


def auth_gate(client):
    status, error, _ = client.request("POST", "/oauth/token", {"grant_type": "http://auth0.com/oauth/grant-type/passwordless/otp", "username": "canvasser@example.test", "otp": "000000", "realm": "email"}, auth=False)
    check(status >= 400 and error.get("error_description"), "wrong OTP uses Auth0 error shape")
    tokens = client.otp_login()
    status, profile, _ = client.request("GET", "/userinfo")
    check(status == 200 and profile["email"] == "canvasser@example.test", "userinfo")
    status, refreshed, _ = client.request("POST", "/oauth/token", {"grant_type": "refresh_token", "client_id": "329jKTvPKBUjOSnY9sYnf0m7Z0gkzTTm", "refresh_token": tokens["refresh_token"]}, auth=False)
    check(status == 200 and refreshed.get("access_token") and "refresh_token" not in refreshed, "non-rotating refresh response")
    other = Client(client.base); other_tokens = other.otp_login("unverified@example.test")
    status, body, _ = other.request("GET", "/api/v1/me")
    check(status == 401 and body == {"detail": "You need to verify your email to access this resource"}, "verify-email 401 bypass contract")
    status, _, _ = other.request("POST", "/api/v1/verification-email", {})
    check(status == 200, "unverified user can resend verification email")

    # Repoint padding appears in the redirect_uri generated by the untouched
    # Auth0.Android SDK. The mock must canonicalize it to the stock manifest's
    # callback path so Android can deliver the code back to RedirectActivity.
    padded = "com.numinar.numinar.auth0://50.39.218.242:19002//////////////android/com.numinar.numinar/callback"
    query = urllib.parse.urlencode({
        "client_id": "329jKTvPKBUjOSnY9sYnf0m7Z0gkzTTm",
        "redirect_uri": padded,
        "response_type": "code",
        "state": "browser-state-test",
        "nonce": "browser-nonce-test",
    })
    form = urllib.parse.urlencode({"email": "canvasser@example.test", "password": "test"}).encode()
    request = urllib.request.Request(client.base + "/authorize?" + query, data=form,
                                     headers={"Content-Type": "application/x-www-form-urlencoded"},
                                     method="POST")
    with urllib.request.urlopen(request, timeout=10) as response:
        landing = response.read().decode()
    canonical = "com.numinar.numinar.auth0://50.39.218.242:19002/android/com.numinar.numinar/callback"
    check(response.status == 200 and canonical in landing and padded not in landing,
          "Web Auth callback path canonicalized for Android intent filter")
    match = re.search(r"code=(mock_ac_[0-9a-f]+)", landing)
    check(match is not None and "state=browser-state-test" in landing,
          "Web Auth landing carries code and state")
    status, web_tokens, _ = client.request("POST", "/oauth/token", {
        "grant_type": "authorization_code", "code": match.group(1),
        "client_id": "329jKTvPKBUjOSnY9sYnf0m7Z0gkzTTm",
        "redirect_uri": padded, "code_verifier": "mock-verifier",
    }, auth=False)
    check(status == 200 and web_tokens.get("access_token"),
          "Web Auth authorization-code exchange")
    status, jwks, _ = client.request("GET", "/.well-known/jwks.json", auth=False)
    check(status == 200 and len(jwks.get("keys", [])) == 1,
          "OpenID JWKS endpoint")
    id_token = web_tokens["id_token"]
    header = jwt.get_unverified_header(id_token)
    key = jwks["keys"][0]
    check(header.get("alg") == "RS256" and header.get("kid") == key.get("kid"),
          "Web Auth ID token uses advertised RS256 key")
    public_key = jwt.algorithms.RSAAlgorithm.from_jwk(json.dumps(key))
    issuer = "http://50.39.218.242:19002" + "/" * 13
    claims = jwt.decode(
        id_token, public_key, algorithms=["RS256"],
        audience="329jKTvPKBUjOSnY9sYnf0m7Z0gkzTTm", issuer=issuer,
    )
    check(claims.get("nonce") == "browser-nonce-test",
          "Web Auth ID token signature, issuer, audience, and nonce")


def core_gate(client):
    client.otp_login()
    status, me, _ = client.request("GET", "/api/v1/me"); check(status == 200 and me["id"], "GET me")
    status, orgs, _ = client.request("GET", "/api/v1/my-orgs-mobile"); check(status == 200 and orgs[0]["selected_state"] == "AK", "GET orgs")
    status, org, _ = client.request("GET", "/api/v2/orgs/" + orgs[0]["id"]); check(status == 200 and org["data_source"], "GET org detail")
    status, projects, _ = client.request("GET", "/api/v3/projects"); check(status == 200 and {p["outreach_type"] for p in projects} >= {"canvass", "call"}, "GET projects")
    project = next(p for p in projects if p["outreach_type"] == "canvass")
    check(project["survey"]["questions"] and project["conditional_survey"], "canvass survey and conditional project fixture")
    dynamic = project["dynamic_survey"]
    mappings = dynamic["survey_mappings"]
    check(dynamic["tag_id"] and mappings and any(m.get("is_default") for m in mappings), "dynamic survey has default mapping")
    dynamic_questions = next(m["survey"]["questions"] for m in mappings if m.get("is_default"))
    check(all(isinstance(q.get("position"), int) and isinstance(q.get("response_set"), list) and all("response" in r and "next_q" in r for r in q["response_set"]) for q in dynamic_questions), "stock question renderer contract")
    status, selected, _ = client.request("GET", "/api/v3/projects/" + project["id"]); check(status == 200 and selected["id"] == project["id"], "GET selected project")
    query = urllib.parse.urlencode({"ignore_contacted": "false", "include_past_contacts": "true", "limit": 10000, "include_tags": "true", "compress": "true"})
    status, body, _ = client.request("GET", f"/api/v2/mobile-app/projects/{project['id']}/voters?{query}")
    columns = json.loads(gzip.decompress(base64.b64decode(body["voters_compressed"])).decode())
    keys = list(columns); voters = [{key: columns[key][index] for key in keys} for index in range(len(columns[keys[0]]))]
    check(status == 200 and 200 <= len(voters) <= 500, "voters_compressed gzip/base64 round-trip")
    first = voters[0]
    check(all(key in first for key in ("house_hold_id", "registration_address_latitude", "registered_party_roll_up", "vh_24_g", "abev_elections", "has_interaction")), "full voter schema")
    check(voters[0]["house_hold_id"] == voters[1]["house_hold_id"] and voters[0]["registration_address_latitude"] == voters[1]["registration_address_latitude"], "household clustering")
    status, nearby, _ = client.request("GET", f"/api/v1/nearby-voters?latitude={first['registration_address_latitude']}&longitude={first['registration_address_longitude']}"); check(status == 200 and nearby, "nearby voters")
    status, found, _ = client.request("GET", "/api/v1/mobile-voter-search?first_name=" + urllib.parse.quote(first["first_name"]) + "&limit=100&offset=0"); check(status == 200 and any(v["id"] == first["id"] for v in found), "voter search")
    for path, label in [(f"/api/v1/voters/{first['id']}/notes", "notes"), (f"/api/v1/voters/{first['id']}/interactions", "activity"), (f"/api/v2/voter_tags/{first['id']}", "tags"), (f"/api/v1/projects/{project['id']}/voters/{first['id']}", "single voter")]:
        status, _, _ = client.request("GET", path); check(status == 200, "per-voter " + label)


def interaction_samples(prefix="gate"):
    def iid(n): return f"{prefix}-{n}-{uuid.uuid4()}"
    return [
        {"id": iid(1), "user_id": "usr_alaska_001", "project_id": "project_canvass_001", "voter_id": "voter_0001", "household_id": "household_0001", "latitude": 61.171, "longitude": -149.913, "user_latitude": "61.172", "user_longitude": "-149.914", "disposition": "canvassed", "survey_type": "canvass", "created_at": "2026-09-22T12:00:00Z", "device_id": "device-test", "is_using_emulator": False, "device_geolocation_enabled": True, "device_geolocation_permission_status": "granted", "call_length": 9},
        {"id": iid(2), "user_id": "usr_alaska_001", "project_id": "project_call_001", "voter_id": "voter_0002", "disposition": "answered", "call_length": 42, "survey_type": "call", "created_at": "2026-09-22T12:00:00Z", "responses": []},
        {"id": iid(3), "user_id": "usr_alaska_001", "project_id": "project_relational_001", "voter_id": "voter_0003", "survey_type": "relational", "survey_id": "survey_relational_001", "responses": [], "created_at": "2026-09-22T12:00:00Z"},
        {"id": iid(4), "user_id": "usr_alaska_001", "org_id": "org_alaska_001", "voter_id": "voter_0004", "tag_id": "tag_support", "value": "Yes", "created_at": "2026-09-22T12:00:00Z", "updated_at": "2026-09-22T12:00:00Z"},
        {"id": iid(5), "project_id": "project_canvass_001", "voter_id": "voter_0005", "value": "Strong supporter", "created_at": "2026-09-22T12:00:00Z"},
    ]


def interactions_gate(client):
    client.otp_login(); samples = interaction_samples()
    expected = ["canvass", "call", "relational", "tag", "notes"]
    for item, kind in zip(samples, expected):
        status, body, _ = client.request("POST", "/api/v1/interactions/batch", [item]); check(status == 200 and body["types"] == [kind], kind + " interaction")
    check(expected[0] == "canvass", "guard-order collision fixture classified canvass before call")
    status, duplicate, _ = client.request("POST", "/api/v1/interactions/batch", [samples[0]]); check(status == 200 and duplicate["duplicates"] == 1, "duplicate client UUID tolerance")
    mixed = []
    for n in range(2): mixed.extend(interaction_samples(f"mixed{n}"))
    status, body, _ = client.request("POST", "/api/v1/interactions/batch", mixed); check(status == 200 and body["accepted"] == 10 and body["types"] == expected * 2, "10-item mixed offline drain")
    status, voter, _ = client.request("GET", "/api/v1/projects/project_canvass_001/voters/voter_0001"); check(status == 200 and voter["has_interaction"] is True, "has_interaction flips server-side")
    status, notes, _ = client.request("GET", "/api/v1/voters/voter_0005/notes"); check(status == 200 and "Strong supporter" in notes, "notes read-back")
    status, tags, _ = client.request("GET", "/api/v2/voter_tags/voter_0004"); check(status == 200 and tags["tags"], "tags read-back")
    status, _, _ = client.request("POST", "/api/v1/canvassing-qa/tracking", {"project_id": "project_canvass_001", "latitude": 61.2, "longitude": -149.8, "device_id": "device-test", "device_geolocation_enabled": True, "device_geolocation_permission_status": "granted", "is_using_emulator": True}); check(status == 200, "QA beacon accepted without emulator gating")
    status, dash, _ = client.request("GET", "/__mock/state", auth=False, basic=True); check(status == 200 and dash["qa_pings"][-1]["is_using_emulator"] is True, "QA beacon stored")


def main():
    parser = argparse.ArgumentParser(); parser.add_argument("gate", choices=("auth", "core", "interactions")); parser.add_argument("base", nargs="?", default="http://127.0.0.1:19002")
    args = parser.parse_args(); client = Client(args.base)
    {"auth": auth_gate, "core": core_gate, "interactions": interactions_gate}[args.gate](client)
    print(f"PASS: {args.gate}")


if __name__ == "__main__":
    try: main()
    except Exception as exc:
        print("FAIL:", exc, file=sys.stderr); raise
